language: r
pandoc_version: 1.19.2.1
sudo: required
cache:
  packages: true
  directories:
  - manuscript/cache

addons:
  apt:
    packages:
      - libgit2-dev

apt_pacakges:
  - r-cran-java
  - libgsl-dev
  - libproj-dev
  - libgdal-dev
  - open-cobol

before_deploy:
  - openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv -in deploy-key.enc -out deploy-key -d

before_install:
  - sudo $(which R) CMD javareconf
  - Rscript -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) { install.packages("BiocManager"); BiocManager::install("Biobase")}'


before_script:
- chmod +x ./_build_and_deploy.sh
- git config --global user.email "tanersirakorn@gmail.com"
- git config --global user.name "Sirakorn Lamyai"
script: ./_build_and_deploy.sh
env:
  global:
  - secure: cRrbyXDpQofuJ3mNYFPsCqO4lTUDFDSsTqVcFPS9fK25iUGsfqxjEjgOAwn4CrRCyalMeX2ERhqQH1SA6++oNxLKO4keGbzvvti9LWAbZuAG5b628+mD4AWOshajILfe6k6jDEsvxt2uAKsbxuBiPQl7jnnN3+DJDzV8tMHr0YZXuD50HU7mzyqE3RZT6AiKSYzNbiPDe8VZatlmiuBtikmevkaOD37EjIAN0GJBD4bv+o2usdOkDTpbZXSueDnsRY1OantndEbH3j50esjJiPRPcFCk1CsX7CiYUyJZOEhjJLYzblVMXHQhuoHpHpQrwRzSwz+ysxEAvr8g3wR9a6HkLyJFu0GiYE4HIWLx9PLd2st+Rq5pRcS3Fx04M2goDVh6nIvF9JZ/5Yk6N6nGYKrEGDVGwWE1tNKQPZChHcaKu0LjVNL1gh09x3oq4BtSoJ1Gsy6NALwFqkUMmOhQtsDVB+XBdR3YB5mW5P/1Ma143oST43uNYiQ8mO5o71KMYX6fVIWbtGHNbIow1NZxWhhpK6PfuwxqfV50/xwUBkxeeEZmYva+P2jO1AXSSZ+nlSigotjL9bn0dY6xOrEmLKCepcJDU6bM2xObQULAdbWeA3LpPnTWM3Lq/RiOKCXcRIAT1KlB49tK1hzanY6GUcRjONLLs+Knd2ryFt2yQik=


